import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai'
import Image from "next/legacy/image"
import anish from "../public/anish.png"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className=" min-h-screen">
          <nav className='py-10 mb-12 flex justify-between md:p-20 lg:p-30'>
            <h1 className='text-xl font-burtons pt-2 md:text-2xl lg:text-3xl'>AnishKulandaisamy</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            <h2 className='text-5xl text-teal-600 font-medium md:text-6xl lg:text-7xl'>Anish</h2>
            <h4 className='text-xl py-2 md:text-2xl lg:text-3xl'>Full Stack Devloper</h4>
            <p className='text-md py-3 leading-8 text-gray-800 md:text-xl lg:text-2xl md:max-w-lg mx-auto'> Aspiring Full stack web developer based in London.
              Freelancer from design to development
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 md:text-6xl lg:text-7xl'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillInstagram/>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 to-cyan-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-120 h-120 lg: w-200 h-200">
            <Image src={anish} layout ='fill' objectFit='cover'  />
          </div>
        </section>
      </main>
    </div>
  )
}
